import type { PlacementCandidateDoc } from "@/lib/firebase";

export const SEED_PLATFORM_CANDIDATES: PlacementCandidateDoc[] = [
  {
    id: "cand-seed-01",
    portfolioId: "portfolio-01",
    userId: "user-seed-01",
    candidateName: "Aditya Verma",
    candidateEmail: "aditya.verma@eng.edu",
    department: "Computer Science & Engineering",
    batch: "2025",
    college: "National Institute of Technology",
    title: "Full-Stack & Distributed Systems Portfolio",
    slug: "aditya-verma",
    published: true,
    github_repo: "aditya-verma/dev-portfolio",
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "Go", "Docker", "System Design"],
    projectsCount: 4,
    readinessScore: 94,
    placementStatus: "Placed",
    placedCompany: "Google (L3 SWE)",
    placedPackage: "34 LPA",
    targetRole: "Software Development Engineer",
    notes:
      "Cleared Google Summer SWE interview. Completed Google Sheets Career Roadmap milestones.",
    createdAt: "2025-01-15T09:30:00.000Z",
    updatedAt: "2026-02-10T14:20:00.000Z",
  },
  {
    id: "cand-seed-02",
    portfolioId: "portfolio-02",
    userId: "user-seed-02",
    candidateName: "Pooja Krishnamurthy",
    candidateEmail: "pooja.k@tech.edu",
    department: "Artificial Intelligence & Data Science",
    batch: "2025",
    college: "College of Engineering",
    title: "AI Engineer & MLOps Portfolio",
    slug: "pooja-ai",
    published: true,
    github_repo: "poojak/ml-portfolio",
    skills: ["Python", "PyTorch", "FastAPI", "TensorFlow", "Kubeflow", "AWS", "MLOps"],
    projectsCount: 3,
    readinessScore: 90,
    placementStatus: "Placed",
    placedCompany: "Microsoft (AI Platform)",
    placedPackage: "31 LPA",
    targetRole: "Machine Learning Engineer",
    notes: "Presented at PyData 2024. Excellent DSA and Deep Learning fundamentals.",
    createdAt: "2025-02-12T11:00:00.000Z",
    updatedAt: "2026-03-01T16:45:00.000Z",
  },
  {
    id: "cand-seed-03",
    portfolioId: "portfolio-03",
    userId: "user-seed-03",
    candidateName: "Rohan Nambiar",
    candidateEmail: "rohan.n@campus.edu",
    department: "Information Technology",
    batch: "2026",
    college: "Institute of Information Technology",
    title: "Cloud Infrastructure & Backend Engineer",
    slug: "rohan-cloud",
    published: true,
    github_repo: "rohann/cloud-native",
    skills: ["Java", "Spring Boot", "Kubernetes", "Kafka", "AWS Lambda", "Redis"],
    projectsCount: 3,
    readinessScore: 86,
    placementStatus: "Interviewing",
    placedCompany: "Amazon (Final Round SDE-1)",
    placedPackage: "Target: 28 LPA",
    targetRole: "Backend Engineer",
    notes: "Currently in Amazon round 3 system design & leadership principles.",
    createdAt: "2026-01-05T08:15:00.000Z",
    updatedAt: "2026-03-12T10:00:00.000Z",
  },
  {
    id: "cand-seed-04",
    portfolioId: "portfolio-04",
    userId: "user-seed-04",
    candidateName: "Ananya Deshmukh",
    candidateEmail: "ananya.d@univ.edu",
    department: "Electronics & Communication Engineering",
    batch: "2025",
    college: "Govt Engineering College",
    title: "Embedded Systems & IoT Architect",
    slug: "ananya-iot",
    published: true,
    github_repo: "ananya-d/iot-portfolio",
    skills: ["C++", "FreeRTOS", "Verilog", "MQTT", "ESP32", "Python", "Linux"],
    projectsCount: 3,
    readinessScore: 88,
    placementStatus: "Placed",
    placedCompany: "Qualcomm (Systems Software)",
    placedPackage: "26 LPA",
    targetRole: "Firmware Engineer",
    notes: "Won Smart India Hackathon. Exceptional hardware-software co-design.",
    createdAt: "2025-03-10T14:30:00.000Z",
    updatedAt: "2026-01-22T09:15:00.000Z",
  },
  {
    id: "cand-seed-05",
    portfolioId: "portfolio-05",
    userId: "user-seed-05",
    candidateName: "Karthik Sundaram",
    candidateEmail: "karthik.s@techuniv.edu",
    department: "Computer Science & Engineering",
    batch: "2026",
    college: "Institute of Technology",
    title: "Competitive Programmer & Frontend Specialist",
    slug: "karthik-dev",
    published: true,
    github_repo: "karthiks/folio-site",
    skills: ["React", "Next.js", "Tailwind CSS", "Data Structures", "GraphQL"],
    projectsCount: 2,
    readinessScore: 82,
    placementStatus: "Ready for Referral",
    placedCompany: "",
    placedPackage: "",
    targetRole: "Frontend Engineer / SDE-1",
    notes: "Codeforces Candidate Master. Actively seeking product-based referrals.",
    createdAt: "2026-02-18T10:00:00.000Z",
    updatedAt: "2026-03-20T11:30:00.000Z",
  },
  {
    id: "cand-seed-06",
    portfolioId: "portfolio-06",
    userId: "user-seed-06",
    candidateName: "Sneha Reddy",
    candidateEmail: "sneha.reddy@campus.edu",
    department: "Computer Science & Engineering",
    batch: "2027",
    college: "Institute of Technology",
    title: "Algorithms & Web Dev Apprentice",
    slug: "sneha-folio",
    published: false,
    github_repo: null,
    skills: ["Python", "JavaScript", "HTML/CSS", "SQL"],
    projectsCount: 1,
    readinessScore: 68,
    placementStatus: "Review Pending",
    placedCompany: "",
    placedPackage: "",
    targetRole: "Software Engineering Intern",
    notes: "Sophomore working through Year 2 Google Roadmap topics.",
    createdAt: "2026-03-01T12:00:00.000Z",
    updatedAt: "2026-03-25T15:00:00.000Z",
  },
  {
    id: "cand-seed-07",
    portfolioId: "portfolio-07",
    userId: "user-seed-07",
    candidateName: "Vikram Malhotra",
    candidateEmail: "vikram.m@tech.ac.in",
    department: "Artificial Intelligence & Data Science",
    batch: "2026",
    college: "State Technological University",
    title: "Computer Vision & LLM Applications",
    slug: "vikram-ai",
    published: true,
    github_repo: "vikram-m/cv-projects",
    skills: ["Python", "OpenCV", "LangChain", "Docker", "HuggingFace", "FastAPI"],
    projectsCount: 3,
    readinessScore: 87,
    placementStatus: "Interviewing",
    placedCompany: "NVIDIA (AI Intern to FTE)",
    placedPackage: "Target: 30 LPA",
    targetRole: "Computer Vision Engineer",
    notes: "Built multi-modal video analytics pipeline for research lab.",
    createdAt: "2026-01-20T10:15:00.000Z",
    updatedAt: "2026-03-28T09:30:00.000Z",
  },
  {
    id: "cand-seed-08",
    portfolioId: "portfolio-08",
    userId: "user-seed-08",
    candidateName: "Meera Krishnan",
    candidateEmail: "meera.k@polytech.edu",
    department: "Information Technology",
    batch: "2025",
    college: "City Polytechnic & Engineering",
    title: "DevSecOps & Cloud Security Portfolio",
    slug: "meera-sec",
    published: true,
    github_repo: "meerak/cloud-sec-ops",
    skills: ["Go", "Kubernetes", "Terraform", "AWS IAM", "Trivy", "Prometheus"],
    projectsCount: 4,
    readinessScore: 92,
    placementStatus: "Placed",
    placedCompany: "Cisco (Security Systems)",
    placedPackage: "25 LPA",
    targetRole: "DevSecOps Engineer",
    notes: "Achieved CKA certification. Top performer in university cybersecurity cohort.",
    createdAt: "2025-02-01T15:00:00.000Z",
    updatedAt: "2026-02-15T18:00:00.000Z",
  },
  {
    id: "cand-seed-09",
    portfolioId: "portfolio-09",
    userId: "user-seed-09",
    candidateName: "Arjun Nair",
    candidateEmail: "arjun.nair@engg.edu",
    department: "Electronics & Communication Engineering",
    batch: "2026",
    college: "Regional Engineering College",
    title: "Signal Processing & Edge Computing",
    slug: "arjun-edge",
    published: true,
    github_repo: "arjunn/edge-dsp",
    skills: ["C", "C++", "MATLAB", "ARM Cortex", "TinyML", "CAN Bus"],
    projectsCount: 2,
    readinessScore: 80,
    placementStatus: "Ready for Referral",
    placedCompany: "",
    placedPackage: "",
    targetRole: "Edge AI / Embedded Systems Engineer",
    notes: "Working on low-power IoT sensing nodes for smart agriculture.",
    createdAt: "2026-02-05T09:45:00.000Z",
    updatedAt: "2026-03-10T14:20:00.000Z",
  },
  {
    id: "cand-seed-10",
    portfolioId: "portfolio-10",
    userId: "user-seed-10",
    candidateName: "Tanvi Patel",
    candidateEmail: "tanvi.p@tech.edu",
    department: "Mechanical & Automation Engineering",
    batch: "2025",
    college: "Institute of Technology & Robotics",
    title: "Robotics Kinematics & ROS Simulation",
    slug: "tanvi-robotics",
    published: true,
    github_repo: "tanvip/ros2-navigation",
    skills: ["ROS 2", "Python", "C++", "Gazebo", "SolidWorks", "Control Systems"],
    projectsCount: 3,
    readinessScore: 85,
    placementStatus: "Placed",
    placedCompany: "Tata Motors (EV & Autonomous)",
    placedPackage: "20 LPA",
    targetRole: "Robotics Controls Engineer",
    notes: "Led university rover team to international finals in robotics.",
    createdAt: "2025-01-28T13:20:00.000Z",
    updatedAt: "2026-02-18T11:00:00.000Z",
  },
  {
    id: "cand-seed-11",
    portfolioId: "portfolio-11",
    userId: "user-seed-11",
    candidateName: "Sameer Joshi",
    candidateEmail: "sameer.j@univ.edu",
    department: "Mechanical & Automation Engineering",
    batch: "2026",
    college: "Institute of Technology & Robotics",
    title: "CAD Modeling & Finite Element Analysis",
    slug: "sameer-cad",
    published: false,
    github_repo: null,
    skills: ["ANSYS", "SolidWorks", "Python", "Additive Manufacturing"],
    projectsCount: 2,
    readinessScore: 74,
    placementStatus: "Ready for Referral",
    placedCompany: "",
    placedPackage: "",
    targetRole: "Mechanical Design Engineer",
    notes: "Completed composite material optimization project.",
    createdAt: "2026-02-14T08:30:00.000Z",
    updatedAt: "2026-03-15T12:00:00.000Z",
  },
  {
    id: "cand-seed-12",
    portfolioId: "portfolio-12",
    userId: "user-seed-12",
    candidateName: "Divya Balasubramanian",
    candidateEmail: "divya.b@univ.edu",
    department: "Computer Science & Engineering",
    batch: "2024",
    college: "Premier Engineering Institute",
    title: "Distributed Databases & High-Throughput Systems",
    slug: "divya-db",
    published: true,
    github_repo: "divyab/raft-consensus",
    skills: ["Go", "Raft", "Distributed Systems", "C++", "Linux Kernel", "gRPC"],
    projectsCount: 4,
    readinessScore: 98,
    placementStatus: "Placed",
    placedCompany: "Uber (Platform Infrastructure)",
    placedPackage: "42 LPA",
    targetRole: "Systems Engineer",
    notes: "Alumni mentor for junior batches. Published open-source raft consensus engine.",
    createdAt: "2024-03-10T10:00:00.000Z",
    updatedAt: "2025-05-15T16:00:00.000Z",
  },
  {
    id: "cand-seed-13",
    portfolioId: "portfolio-13",
    userId: "user-seed-13",
    candidateName: "Harsh Vardhan",
    candidateEmail: "harsh.v@campus.edu",
    department: "Information Technology",
    batch: "2024",
    college: "Institute of Information Technology",
    title: "Full-Stack Microservices & Observability",
    slug: "harsh-infra",
    published: true,
    github_repo: "harshv/microservices-platform",
    skills: ["TypeScript", "NestJS", "Kubernetes", "Datadog", "PostgreSQL", "Kafka"],
    projectsCount: 3,
    readinessScore: 91,
    placementStatus: "Placed",
    placedCompany: "Razorpay (Fintech Platform)",
    placedPackage: "29 LPA",
    targetRole: "Backend Engineer",
    notes: "High concurrency payment gateway mock architecture project.",
    createdAt: "2024-04-12T11:20:00.000Z",
    updatedAt: "2025-06-20T14:30:00.000Z",
  },
  {
    id: "cand-seed-14",
    portfolioId: "portfolio-14",
    userId: "user-seed-14",
    candidateName: "Ishita Sen",
    candidateEmail: "ishita.s@univ.edu",
    department: "Artificial Intelligence & Data Science",
    batch: "2027",
    college: "National Institute of Technology",
    title: "Statistical Modeling & Python Analytics",
    slug: "ishita-analytics",
    published: false,
    github_repo: null,
    skills: ["Python", "Pandas", "Scikit-Learn", "Tableau", "SQL", "Statistics"],
    projectsCount: 1,
    readinessScore: 70,
    placementStatus: "Review Pending",
    placedCompany: "",
    placedPackage: "",
    targetRole: "Data Analyst Intern",
    notes: "Sophomore with exceptional math and statistics background.",
    createdAt: "2026-03-05T14:00:00.000Z",
    updatedAt: "2026-03-29T10:15:00.000Z",
  },
  {
    id: "cand-seed-15",
    portfolioId: "portfolio-15",
    userId: "user-seed-15",
    candidateName: "Nikhil Chawla",
    candidateEmail: "nikhil.c@eng.edu",
    department: "Computer Science & Engineering",
    batch: "2028",
    college: "State Technological University",
    title: "Introductory Web Development & C++ Basics",
    slug: "nikhil-starter",
    published: true,
    github_repo: "nikhilc/freshman-web",
    skills: ["C++", "HTML/CSS", "JavaScript", "Git"],
    projectsCount: 1,
    readinessScore: 60,
    placementStatus: "Profile In Progress",
    placedCompany: "",
    placedPackage: "",
    targetRole: "Aspiring Software Engineer",
    notes: "Freshman onboarded to start Year 1 engineering milestones early.",
    createdAt: "2026-03-22T08:00:00.000Z",
    updatedAt: "2026-03-30T17:00:00.000Z",
  },
];
