/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DemoSakuraRouteImport } from './routes/demo.sakura'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AuthenticatedEditorIdRouteImport } from './routes/_authenticated/editor.$id'
import { Route as ApiAuthGithubRouteImport } from './routes/api/auth/github'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as OauthGithubReturnRouteImport } from './routes/oauth/github/return'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const DemoSakuraRoute = DemoSakuraRouteImport.update({
  id: '/demo/sakura',
  path: '/demo/sakura',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEditorIdRoute = AuthenticatedEditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAuthGithubRoute = ApiAuthGithubRouteImport.update({
  id: '/api/auth/github',
  path: '/api/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGithubReturnRoute = OauthGithubReturnRouteImport.update({
  id: '/oauth/github/return',
  path: '/oauth/github/return',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/create': typeof CreateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/demo/sakura': typeof DemoSakuraRoute
  '/p/$slug': typeof PSlugRoute
  '/editor/$id': typeof AuthenticatedEditorIdRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/oauth/github/return': typeof OauthGithubReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/create': typeof CreateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/demo/sakura': typeof DemoSakuraRoute
  '/p/$slug': typeof PSlugRoute
  '/editor/$id': typeof AuthenticatedEditorIdRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/oauth/github/return': typeof OauthGithubReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/create': typeof CreateRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/demo/sakura': typeof DemoSakuraRoute
  '/p/$slug': typeof PSlugRoute
  '/_authenticated/editor/$id': typeof AuthenticatedEditorIdRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/oauth/github/return': typeof OauthGithubReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/create'
    | '/dashboard'
    | '/auth/callback'
    | '/demo/sakura'
    | '/p/$slug'
    | '/editor/$id'
    | '/api/auth/github'
    | '/api/auth/google'
    | '/oauth/github/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create'
    | '/dashboard'
    | '/auth/callback'
    | '/demo/sakura'
    | '/p/$slug'
    | '/editor/$id'
    | '/api/auth/github'
    | '/api/auth/google'
    | '/oauth/github/return'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/create'
    | '/_authenticated/dashboard'
    | '/auth/callback'
    | '/demo/sakura'
    | '/p/$slug'
    | '/_authenticated/editor/$id'
    | '/api/auth/github'
    | '/api/auth/google'
    | '/oauth/github/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CreateRoute: typeof CreateRoute
  DemoSakuraRoute: typeof DemoSakuraRoute
  PSlugRoute: typeof PSlugRoute
  ApiAuthGithubRoute: typeof ApiAuthGithubRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  OauthGithubReturnRoute: typeof OauthGithubReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/demo/sakura': {
      id: '/demo/sakura'
      path: '/demo/sakura'
      fullPath: '/demo/sakura'
      preLoaderRoute: typeof DemoSakuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/editor/$id': {
      id: '/_authenticated/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof AuthenticatedEditorIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/auth/github': {
      id: '/api/auth/github'
      path: '/api/auth/github'
      fullPath: '/api/auth/github'
      preLoaderRoute: typeof ApiAuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/github/return': {
      id: '/oauth/github/return'
      path: '/oauth/github/return'
      fullPath: '/oauth/github/return'
      preLoaderRoute: typeof OauthGithubReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEditorIdRoute: typeof AuthenticatedEditorIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEditorIdRoute: AuthenticatedEditorIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CreateRoute: CreateRoute,
  DemoSakuraRoute: DemoSakuraRoute,
  PSlugRoute: PSlugRoute,
  ApiAuthGithubRoute: ApiAuthGithubRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  OauthGithubReturnRoute: OauthGithubReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
